### ISSUE TITLE
Great idea but appears non-functional

### ISSUE THREAD

**Issue by VibroAxe** [Matthew1471/MyEE-API#1]
Hi Matt

Great idea, found this looking to do the same thing but I'm getting a bunch of errors. Before I spend some time debugging this appears to be using id.ee rather than auth.ee which I see when I go on the web. 

I'm wondering if you are still using this and it works (in such case I'll get debugging) or if you've stopped using it and ee have changed their site since?

Thanks anyways

**Comment by Matthew1471** [comment]
Hi @VibroAxe, both of the SIMs on my account went unlimited data at contract renewal so I stopped running this via cron (interestingly while the official website form blocked the gifting requests to unlimited data users, the API still transferred the data even to an unlimited data SIM).

I've just logged in to MyEE via the website and watched Developer Tools. The auth looks like it's slightly changed (the username and password are split and the HTTP POST to enter it now requires JavaScript... so the first couple of URLs need adjusting) but the rest seems exactly the same as before. I think they used to use solely ApiGee Auth but now it looks like that points to use Azure AD C2B Auth ("..im-sso:eeauthprod.onmicrosoft.com"). That's fundamentally what's changed and why.

The SelfAsserted URL is where the username and password gets POSTed with some of the URL params from JavaScript.

I wrote this to not follow redirects and dump as many of the cookies that weren't mandatory as possible... I wanted every single byte over the network to be important... but this made it more brittle.

I'm getting a 200 back from the login service now.. just need to find a few more strings and I should have a prototype out soon.

**Comment by VibroAxe** [comment]
Fantastic, thanks this will be really useful and saves me a lot of reverse engineering you've already done! If there's anything I can do to help, hit me up

**Comment by Matthew1471** [comment]
I'm calling it a night, but this is what I have so far : https://github.com/Matthew1471/MyEE-API/commit/9e24f6cdc7396352405e6585e5c2b12a0f47b88c

I am not getting the same response as the web-browser gets to the username being input.. I know I'm doing it in 1 stage instead of 2 but it's not even returning my username in the "confirmed" after the "SelfAsserted".

AttributeFields would have "PRE":" with my e-mail address when done in the web-browser.. so it's not submitting the form right despite the 200 status code and text back.

Once that is correct the "confirmed" (or second "confirmed" if this does have to be split into 2 HTTP "SelfAsserted"s) contains a hidden HTML form with a "code" and a "state".. this is given to id.ee.co.uk/login along with a session state (which I've probably commented out in the debug code) which sends you to id.ee.co.uk/auth and the rest of the journey appears identical from then on.

EE seem to only ever add new systems in and never remove the old ones (bet their operations team have fun!).. so the fact there's now a further depdency on auth.ee and still the original id.ee does not surprise me... and the amount of cookies being bounced back and for and the number of HTTP requests/redirects just to login is now frankly staggering. I'd be keen to make this script continue to just strip it back to the minimums.

**Comment by Matthew1471** [comment]
Well that was an interesting and fun experience (secret ways to validate sessions, pages on the MyEE website that have moved but are still referenced on the site causing excessive HTTP Redirects)..

The latest files now resolve your issue with the library not supporting the Azure AD B2C changes BT/EE seemed to implement in Jan 2022.

Please let me know if not. It's now lighter and more responsive than the official MyEE website!

**Comment by VibroAxe** [comment]
```
* Logging into My EE.
* Getting data gifting token.
* Checking data gifting allowances:
  - Can gift up to 65.2 GB out of the 100/120 GB gifting allowance after 2.8 GB data usage.
* Downloaded data gifting history:
{
    "recentGifts": [
        {
            *snip*
        }
    ],
    "olderGifts": []
}
* Performing data gifting of 65.0GB.
```

Seems to be working perfectly. thank you!

**Comment by Matthew1471** [comment]
You're welcome 😄.

The data gifting history request is not integral to data gifting (I just left it in to complete the demonstration of the API). You can save a HTTP request by commenting out those 2 lines (currently lines 68 and 69 of [MyEEDataGift.py](https://github.com/Matthew1471/MyEE-API/blob/21769eca481da3b98c2f5fb23549ad4bdad681df/MyEEDataGift.py#L67-L69)) if that's important to you.

Originally, I was going to make this a fully featured wrapper for everything worth automating on MyEE, but it was only for data gifting that I ever logged in for.
